-- Database export: phys_lab_3d
-- Date: 2026-07-19 09:31:17
-- Generated by DBX
--
-- Database schema: phys_lab_3d
-- PostgreSQL 16（无需 pgvector）

CREATE SEQUENCE IF NOT EXISTS "public"."announcements_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE SEQUENCE IF NOT EXISTS "public"."experiment_views_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE SEQUENCE IF NOT EXISTS "public"."knowledge_pages_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."knowledge_pages" (
  "id" bigint NOT NULL DEFAULT nextval('knowledge_pages_id_seq'::regclass),
  "title" character varying(200) NOT NULL,
  "description" character varying(500),
  "content" text NOT NULL,
  "sort_order" integer NOT NULL DEFAULT 0,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

COMMENT ON TABLE "public"."knowledge_pages" IS 'AI 知识页（标题+描述供目录工具，正文按需拉取）';
COMMENT ON COLUMN "public"."knowledge_pages"."id" IS '知识页 ID，自增主键';
COMMENT ON COLUMN "public"."knowledge_pages"."title" IS '文档名';
COMMENT ON COLUMN "public"."knowledge_pages"."description" IS '摘要，供 AI 列表选型';
COMMENT ON COLUMN "public"."knowledge_pages"."content" IS '正文（markdown/纯文本）';
COMMENT ON COLUMN "public"."knowledge_pages"."sort_order" IS '保留字段，列表默认按 update_time 排序';
COMMENT ON COLUMN "public"."knowledge_pages"."create_time" IS '创建时间，插入时自动填充';
COMMENT ON COLUMN "public"."knowledge_pages"."update_time" IS '更新时间，插入/更新时自动填充';

CREATE SEQUENCE IF NOT EXISTS "public"."subject_types_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."subject_types" (
  "id" bigint NOT NULL DEFAULT nextval('subject_types_id_seq'::regclass),
  "code" character varying(40) NOT NULL,
  "label" character varying(40) NOT NULL,
  "description" text,
  "sort_order" integer NOT NULL DEFAULT 0,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

COMMENT ON TABLE "public"."subject_types" IS '物理子学科分类（力学、光学等）';
COMMENT ON COLUMN "public"."subject_types"."id" IS '学科类型 ID，自增主键';
COMMENT ON COLUMN "public"."subject_types"."code" IS '枚举代码，如 MECHANICS、QUANTUM，与 experiments.subject_type 冗余字段同步';
COMMENT ON COLUMN "public"."subject_types"."label" IS '中文展示名，如 力学、量子';
COMMENT ON COLUMN "public"."subject_types"."description" IS '学科说明（可选）';
COMMENT ON COLUMN "public"."subject_types"."sort_order" IS '排序权重，越小越靠前';
COMMENT ON COLUMN "public"."subject_types"."create_time" IS '创建时间，插入时自动填充';
COMMENT ON COLUMN "public"."subject_types"."update_time" IS '更新时间，插入/更新时自动填充';
CREATE UNIQUE INDEX "uk_subject_types_code" ON "public"."subject_types" USING btree ("code");

CREATE SEQUENCE IF NOT EXISTS "public"."ai_chat_messages_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."ai_chat_messages" (
  "id" bigint NOT NULL DEFAULT nextval('ai_chat_messages_id_seq'::regclass),
  "session_id" bigint NOT NULL,
  "role" character varying(20) NOT NULL,
  "content" text NOT NULL,
  "context_json" jsonb,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

COMMENT ON TABLE "public"."ai_chat_messages" IS 'AI 辅导会话消息（用户提问 / 助手回复）';
COMMENT ON COLUMN "public"."ai_chat_messages"."id" IS '消息 ID，自增主键';
COMMENT ON COLUMN "public"."ai_chat_messages"."session_id" IS '会话 ID，逻辑关联 ai_chat_sessions(id)';
COMMENT ON COLUMN "public"."ai_chat_messages"."role" IS '角色：user / assistant / thinking / tool_call / tool_result';
COMMENT ON COLUMN "public"."ai_chat_messages"."content" IS '消息正文';
COMMENT ON COLUMN "public"."ai_chat_messages"."context_json" IS '发消息时的页面上下文（可选 JSONB）';
COMMENT ON COLUMN "public"."ai_chat_messages"."create_time" IS '创建时间，插入时自动填充';
CREATE INDEX "idx_ai_chat_messages_session_id" ON "public"."ai_chat_messages" USING btree ("session_id", "id");

CREATE SEQUENCE IF NOT EXISTS "public"."experiment_comments_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."experiment_comments" (
  "id" bigint NOT NULL DEFAULT nextval('experiment_comments_id_seq'::regclass),
  "experiment_id" bigint NOT NULL,
  "owner_id" bigint NOT NULL,
  "owner_type" smallint NOT NULL,
  "root_id" bigint,
  "reply_to_id" bigint,
  "content" character varying(1000) NOT NULL,
  "like_count" bigint NOT NULL DEFAULT 0,
  "status" character varying(20) NOT NULL DEFAULT 'VISIBLE'::character varying,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

COMMENT ON TABLE "public"."experiment_comments" IS '实验评论与楼中楼回复';
COMMENT ON COLUMN "public"."experiment_comments"."id" IS '评论 ID，自增主键';
COMMENT ON COLUMN "public"."experiment_comments"."experiment_id" IS '实验 ID，逻辑关联 experiments(id)';
COMMENT ON COLUMN "public"."experiment_comments"."owner_id" IS '作者 ID：owner_type=0 时为 users.id；=1 时为 admins.id';
COMMENT ON COLUMN "public"."experiment_comments"."owner_type" IS '作者类型：0=用户 USER，1=管理员 ADMIN';
COMMENT ON COLUMN "public"."experiment_comments"."root_id" IS '所属一级评论 ID；一级评论为 NULL；楼内回复均指向该楼一级评论';
COMMENT ON COLUMN "public"."experiment_comments"."reply_to_id" IS '直接回复的评论 ID；一级评论为 NULL；可指向一级或同楼任意回复';
COMMENT ON COLUMN "public"."experiment_comments"."content" IS '评论正文，1–1000 字';
COMMENT ON COLUMN "public"."experiment_comments"."like_count" IS '点赞数（冗余统计）';
COMMENT ON COLUMN "public"."experiment_comments"."status" IS '可见状态：VISIBLE / HIDDEN / DELETED';
COMMENT ON COLUMN "public"."experiment_comments"."create_time" IS '创建时间，插入时自动填充';
COMMENT ON COLUMN "public"."experiment_comments"."update_time" IS '更新时间，插入/更新时自动填充';
CREATE INDEX "idx_experiment_comments_experiment_created" ON "public"."experiment_comments" USING btree ("experiment_id", "create_time");
CREATE INDEX "idx_experiment_comments_owner" ON "public"."experiment_comments" USING btree ("owner_type", "owner_id");
CREATE INDEX "idx_experiment_comments_root" ON "public"."experiment_comments" USING btree ("root_id", "create_time");

CREATE TABLE "public"."experiment_views" (
  "id" bigint NOT NULL DEFAULT nextval('experiment_views_id_seq'::regclass),
  "experiment_id" bigint NOT NULL,
  "user_id" bigint,
  "viewed_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

COMMENT ON TABLE "public"."experiment_views" IS '实验详情页访问日志（每次打开记一行）';
COMMENT ON COLUMN "public"."experiment_views"."id" IS '访问记录 ID，自增主键';
COMMENT ON COLUMN "public"."experiment_views"."experiment_id" IS '实验 ID，逻辑关联 experiments(id)';
COMMENT ON COLUMN "public"."experiment_views"."user_id" IS '登录用户 ID，逻辑关联 users(id)；游客为空';
COMMENT ON COLUMN "public"."experiment_views"."viewed_at" IS '访问时间';
CREATE INDEX "idx_experiment_views_experiment_viewed" ON "public"."experiment_views" USING btree ("experiment_id", "viewed_at");
CREATE INDEX "idx_experiment_views_viewed_at" ON "public"."experiment_views" USING btree ("viewed_at");

CREATE SEQUENCE IF NOT EXISTS "public"."experiments_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."experiments" (
  "id" bigint NOT NULL DEFAULT nextval('experiments_id_seq'::regclass),
  "route" character varying(64) NOT NULL,
  "title" character varying(120) NOT NULL,
  "subject_type" character varying(40) NOT NULL,
  "description" text NOT NULL,
  "cover_url" character varying(512),
  "topics" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "status" character varying(20) NOT NULL DEFAULT 'PUBLISHED'::character varying,
  "visitor_count" bigint NOT NULL DEFAULT 0,
  "favorite_count" bigint NOT NULL DEFAULT 0,
  "view_count" bigint NOT NULL DEFAULT 0,
  "comment_count" bigint NOT NULL DEFAULT 0,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "subject_type_id" bigint NOT NULL,
  PRIMARY KEY ("id")
);

COMMENT ON TABLE "public"."experiments" IS '3D 物理实验内容与冗余统计字段';
COMMENT ON COLUMN "public"."experiments"."id" IS '实验 ID，自增主键';
COMMENT ON COLUMN "public"."experiments"."route" IS '路由 slug，唯一，与用户端 3D 页面 registry key 一致';
COMMENT ON COLUMN "public"."experiments"."title" IS '实验标题';
COMMENT ON COLUMN "public"."experiments"."subject_type" IS '物理子学科 code 冗余字段（与 subject_types.code 同步，便于查询）';
COMMENT ON COLUMN "public"."experiments"."description" IS '实验简介';
COMMENT ON COLUMN "public"."experiments"."cover_url" IS '封面 URL（MinIO 或外链）；为空时前端 fallback';
COMMENT ON COLUMN "public"."experiments"."topics" IS '标签数组（JSONB）';
COMMENT ON COLUMN "public"."experiments"."status" IS '发布状态：PUBLISHED / DRAFT';
COMMENT ON COLUMN "public"."experiments"."visitor_count" IS '访客数（冗余统计，预留）';
COMMENT ON COLUMN "public"."experiments"."favorite_count" IS '收藏数（冗余统计）';
COMMENT ON COLUMN "public"."experiments"."view_count" IS '浏览量（冗余统计，与 experiment_views 同步累加）';
COMMENT ON COLUMN "public"."experiments"."comment_count" IS '评论数（冗余统计）';
COMMENT ON COLUMN "public"."experiments"."create_time" IS '创建时间，插入时自动填充';
COMMENT ON COLUMN "public"."experiments"."update_time" IS '更新时间，插入/更新时自动填充';
COMMENT ON COLUMN "public"."experiments"."subject_type_id" IS '物理子学科 ID，逻辑关联 subject_types(id)';
CREATE UNIQUE INDEX "uk_experiments_route" ON "public"."experiments" USING btree ("route");

CREATE SEQUENCE IF NOT EXISTS "public"."ai_chat_sessions_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."ai_chat_sessions" (
  "id" bigint NOT NULL DEFAULT nextval('ai_chat_sessions_id_seq'::regclass),
  "owner_id" bigint NOT NULL,
  "owner_type" smallint NOT NULL,
  "title" character varying(200) NOT NULL DEFAULT '新对话'::character varying,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "context_summary" text,
  "summary_until_msg_id" bigint,
  PRIMARY KEY ("id")
);

COMMENT ON TABLE "public"."ai_chat_sessions" IS 'AI 辅导会话';
COMMENT ON COLUMN "public"."ai_chat_sessions"."id" IS '会话 ID，自增主键';
COMMENT ON COLUMN "public"."ai_chat_sessions"."owner_id" IS '所有者 ID：owner_type=0 为 users.id；=1 为 admins.id';
COMMENT ON COLUMN "public"."ai_chat_sessions"."owner_type" IS '所有者类型：0=用户 USER，1=管理员 ADMIN';
COMMENT ON COLUMN "public"."ai_chat_sessions"."title" IS '会话标题（可用首条用户消息截断）';
COMMENT ON COLUMN "public"."ai_chat_sessions"."create_time" IS '创建时间，插入时自动填充';
COMMENT ON COLUMN "public"."ai_chat_sessions"."update_time" IS '最近消息时间，插入/更新时自动填充';
COMMENT ON COLUMN "public"."ai_chat_sessions"."context_summary" IS '滚动会话摘要正文';
COMMENT ON COLUMN "public"."ai_chat_sessions"."summary_until_msg_id" IS '摘要已覆盖到的消息 id（含），之后的对话原文仍可入模';
CREATE INDEX "idx_ai_chat_sessions_owner_updated" ON "public"."ai_chat_sessions" USING btree ("owner_type", "owner_id", "update_time");

CREATE SEQUENCE IF NOT EXISTS "public"."admins_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."admins" (
  "id" bigint NOT NULL DEFAULT nextval('admins_id_seq'::regclass),
  "username" character varying(20) NOT NULL,
  "password_hash" character varying(255) NOT NULL,
  "display_name" character varying(40) NOT NULL,
  "avatar_url" character varying(512),
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

COMMENT ON TABLE "public"."admins" IS '管理端账号';
COMMENT ON COLUMN "public"."admins"."id" IS '管理员 ID，自增主键';
COMMENT ON COLUMN "public"."admins"."username" IS '登录用户名，唯一';
COMMENT ON COLUMN "public"."admins"."password_hash" IS '密码哈希（BCrypt）';
COMMENT ON COLUMN "public"."admins"."display_name" IS '后台展示名';
COMMENT ON COLUMN "public"."admins"."avatar_url" IS '头像地址，可选；为空时前端用 display_name 首字展示';
COMMENT ON COLUMN "public"."admins"."create_time" IS '创建时间，插入时自动填充';
COMMENT ON COLUMN "public"."admins"."update_time" IS '更新时间，插入/更新时自动填充';
CREATE UNIQUE INDEX "uk_admins_username" ON "public"."admins" USING btree ("username");

CREATE TABLE "public"."announcements" (
  "id" bigint NOT NULL DEFAULT nextval('announcements_id_seq'::regclass),
  "title" character varying(100) NOT NULL,
  "content" text NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

COMMENT ON TABLE "public"."announcements" IS '平台公告';
COMMENT ON COLUMN "public"."announcements"."id" IS '公告 ID，自增主键';
COMMENT ON COLUMN "public"."announcements"."title" IS '公告标题';
COMMENT ON COLUMN "public"."announcements"."content" IS '公告正文';
COMMENT ON COLUMN "public"."announcements"."create_time" IS '创建时间，插入时自动填充';
COMMENT ON COLUMN "public"."announcements"."update_time" IS '更新时间，插入/更新时自动填充';
CREATE INDEX "idx_announcements_create_time" ON "public"."announcements" USING btree ("create_time");

CREATE SEQUENCE IF NOT EXISTS "public"."example_questions_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."example_questions" (
  "id" bigint NOT NULL DEFAULT nextval('example_questions_id_seq'::regclass),
  "title" character varying(100) NOT NULL,
  "description" character varying(200),
  "question" character varying(500) NOT NULL,
  "sort_order" integer NOT NULL DEFAULT 0,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

COMMENT ON TABLE "public"."example_questions" IS 'AI 对话示例问题（用户端欢迎区可选）';
COMMENT ON COLUMN "public"."example_questions"."id" IS '示例 ID，自增主键';
COMMENT ON COLUMN "public"."example_questions"."title" IS '卡片标题';
COMMENT ON COLUMN "public"."example_questions"."description" IS '简短描述（可选）';
COMMENT ON COLUMN "public"."example_questions"."question" IS '点击后填入/发送的完整问题文案';
COMMENT ON COLUMN "public"."example_questions"."sort_order" IS '排序权重，越小越靠前';
COMMENT ON COLUMN "public"."example_questions"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."example_questions"."update_time" IS '更新时间';
CREATE INDEX "idx_example_questions_sort" ON "public"."example_questions" USING btree ("sort_order", "id");

CREATE SEQUENCE IF NOT EXISTS "public"."experiment_comment_likes_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."experiment_comment_likes" (
  "id" bigint NOT NULL DEFAULT nextval('experiment_comment_likes_id_seq'::regclass),
  "comment_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

COMMENT ON TABLE "public"."experiment_comment_likes" IS '实验评论点赞记录';
COMMENT ON COLUMN "public"."experiment_comment_likes"."id" IS '点赞记录 ID，自增主键';
COMMENT ON COLUMN "public"."experiment_comment_likes"."comment_id" IS '评论 ID，逻辑关联 experiment_comments(id)';
COMMENT ON COLUMN "public"."experiment_comment_likes"."user_id" IS '用户 ID，逻辑关联 users(id)';
COMMENT ON COLUMN "public"."experiment_comment_likes"."create_time" IS '点赞时间，插入时自动填充';
CREATE INDEX "idx_experiment_comment_likes_user" ON "public"."experiment_comment_likes" USING btree ("user_id");
CREATE UNIQUE INDEX "uk_experiment_comment_likes_comment_user" ON "public"."experiment_comment_likes" USING btree ("comment_id", "user_id");

CREATE SEQUENCE IF NOT EXISTS "public"."users_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."users" (
  "id" bigint NOT NULL DEFAULT nextval('users_id_seq'::regclass),
  "username" character varying(20) NOT NULL,
  "password_hash" character varying(255) NOT NULL,
  "nickname" character varying(20) NOT NULL,
  "avatar_url" character varying(512),
  "status" character varying(20) NOT NULL DEFAULT 'ENABLED'::character varying,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

COMMENT ON TABLE "public"."users" IS '用户端账号';
COMMENT ON COLUMN "public"."users"."id" IS '用户 ID，自增主键';
COMMENT ON COLUMN "public"."users"."username" IS '登录用户名，唯一，长度 3–20';
COMMENT ON COLUMN "public"."users"."password_hash" IS '密码哈希（BCrypt）';
COMMENT ON COLUMN "public"."users"."nickname" IS '显示昵称；注册时默认写入 username';
COMMENT ON COLUMN "public"."users"."avatar_url" IS '头像地址，可选；为空时前端取 username 前 2 个字符展示文字头像';
COMMENT ON COLUMN "public"."users"."status" IS '账号状态：ENABLED 正常 / DISABLED 禁用（封号）';
COMMENT ON COLUMN "public"."users"."create_time" IS '创建时间，插入时自动填充';
COMMENT ON COLUMN "public"."users"."update_time" IS '更新时间，插入/更新时自动填充';
CREATE UNIQUE INDEX "uk_users_username" ON "public"."users" USING btree ("username");

CREATE SEQUENCE IF NOT EXISTS "public"."experiment_favorites_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."experiment_favorites" (
  "id" bigint NOT NULL DEFAULT nextval('experiment_favorites_id_seq'::regclass),
  "user_id" bigint NOT NULL,
  "experiment_id" bigint NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

COMMENT ON TABLE "public"."experiment_favorites" IS '用户收藏实验记录';
COMMENT ON COLUMN "public"."experiment_favorites"."id" IS '收藏记录 ID，自增主键';
COMMENT ON COLUMN "public"."experiment_favorites"."user_id" IS '用户 ID，逻辑关联 users(id)';
COMMENT ON COLUMN "public"."experiment_favorites"."experiment_id" IS '实验 ID，逻辑关联 experiments(id)';
COMMENT ON COLUMN "public"."experiment_favorites"."create_time" IS '收藏时间，插入时自动填充';
CREATE UNIQUE INDEX "uk_experiment_favorites_user_experiment" ON "public"."experiment_favorites" USING btree ("user_id", "experiment_id");

ALTER SEQUENCE "public"."admins_id_seq" OWNED BY "public"."admins"."id";

ALTER SEQUENCE "public"."example_questions_id_seq" OWNED BY "public"."example_questions"."id";

ALTER SEQUENCE "public"."ai_chat_messages_id_seq" OWNED BY "public"."ai_chat_messages"."id";

ALTER SEQUENCE "public"."ai_chat_sessions_id_seq" OWNED BY "public"."ai_chat_sessions"."id";

ALTER SEQUENCE "public"."experiment_comment_likes_id_seq" OWNED BY "public"."experiment_comment_likes"."id";

ALTER SEQUENCE "public"."experiment_comments_id_seq" OWNED BY "public"."experiment_comments"."id";

ALTER SEQUENCE "public"."experiment_favorites_id_seq" OWNED BY "public"."experiment_favorites"."id";

ALTER SEQUENCE "public"."experiments_id_seq" OWNED BY "public"."experiments"."id";

ALTER SEQUENCE "public"."knowledge_pages_id_seq" OWNED BY "public"."knowledge_pages"."id";

ALTER SEQUENCE "public"."subject_types_id_seq" OWNED BY "public"."subject_types"."id";

ALTER SEQUENCE "public"."users_id_seq" OWNED BY "public"."users"."id";

SELECT setval('"public"."admins_id_seq"', GREATEST(COALESCE(MAX("id"), 2), 2), true) FROM "public"."admins";

SELECT setval('"public"."ai_chat_messages_id_seq"', GREATEST(COALESCE(MAX("id"), 34), 34), true) FROM "public"."ai_chat_messages";

SELECT setval('"public"."ai_chat_sessions_id_seq"', GREATEST(COALESCE(MAX("id"), 21), 21), true) FROM "public"."ai_chat_sessions";

SELECT setval('"public"."announcements_id_seq"', 2, true);

SELECT setval('"public"."experiment_comment_likes_id_seq"', GREATEST(COALESCE(MAX("id"), 5), 5), true) FROM "public"."experiment_comment_likes";

SELECT setval('"public"."experiment_comments_id_seq"', GREATEST(COALESCE(MAX("id"), 7), 7), true) FROM "public"."experiment_comments";

SELECT setval('"public"."experiment_favorites_id_seq"', GREATEST(COALESCE(MAX("id"), 5), 5), true) FROM "public"."experiment_favorites";

SELECT setval('"public"."experiments_id_seq"', GREATEST(COALESCE(MAX("id"), 13), 13), true) FROM "public"."experiments";

SELECT setval('"public"."knowledge_pages_id_seq"', GREATEST(COALESCE(MAX("id"), 1), 1), true) FROM "public"."knowledge_pages";

SELECT setval('"public"."subject_types_id_seq"', GREATEST(COALESCE(MAX("id"), 16), 16), true) FROM "public"."subject_types";

SELECT setval('"public"."users_id_seq"', GREATEST(COALESCE(MAX("id"), 3), 3), true) FROM "public"."users";

