-- Database export: phys_lab_3d
-- Date: 2026-07-19 08:54:46
-- Generated by DBX

CREATE SEQUENCE IF NOT EXISTS "public"."announcements_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE SEQUENCE IF NOT EXISTS "public"."admins_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."admins" (
  "id" bigint NOT NULL DEFAULT nextval('admins_id_seq'::regclass),
  "username" character varying(20) NOT NULL,
  "password_hash" character varying(255) NOT NULL,
  "display_name" character varying(40) NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

COMMENT ON COLUMN "public"."admins"."id" IS '管理员 ID，自增主键';
COMMENT ON COLUMN "public"."admins"."username" IS '登录用户名，唯一';
COMMENT ON COLUMN "public"."admins"."password_hash" IS '密码哈希（BCrypt）';
COMMENT ON COLUMN "public"."admins"."display_name" IS '后台展示名';
COMMENT ON COLUMN "public"."admins"."create_time" IS '创建时间，插入时自动填充';
COMMENT ON COLUMN "public"."admins"."update_time" IS '更新时间，插入/更新时自动填充';
CREATE UNIQUE INDEX "uk_admins_username" ON "public"."admins" USING btree ("username");;

CREATE SEQUENCE IF NOT EXISTS "public"."experiment_comments_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."experiment_comments" (
  "id" bigint NOT NULL DEFAULT nextval('experiment_comments_id_seq'::regclass),
  "experiment_id" bigint NOT NULL,
  "owner_id" bigint NOT NULL,
  "owner_type" smallint NOT NULL,
  "root_id" bigint,
  "reply_to_id" bigint,
  "content" character varying(1000) NOT NULL,
  "like_count" bigint NOT NULL DEFAULT 0,
  "status" character varying(20) NOT NULL DEFAULT 'VISIBLE'::character varying,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

COMMENT ON COLUMN "public"."experiment_comments"."id" IS '评论 ID，自增主键';
COMMENT ON COLUMN "public"."experiment_comments"."experiment_id" IS '实验 ID，逻辑关联 experiments(id)';
COMMENT ON COLUMN "public"."experiment_comments"."owner_id" IS '作者 ID：owner_type=0 时为 users.id；=1 时为 admins.id';
COMMENT ON COLUMN "public"."experiment_comments"."owner_type" IS '作者类型：0=用户 USER，1=管理员 ADMIN';
COMMENT ON COLUMN "public"."experiment_comments"."root_id" IS '所属一级评论 ID；一级评论为 NULL；楼内回复均指向该楼一级评论';
COMMENT ON COLUMN "public"."experiment_comments"."reply_to_id" IS '直接回复的评论 ID；一级评论为 NULL；可指向一级或同楼任意回复';
COMMENT ON COLUMN "public"."experiment_comments"."content" IS '评论正文，1–1000 字';
COMMENT ON COLUMN "public"."experiment_comments"."like_count" IS '点赞数（冗余统计）';
COMMENT ON COLUMN "public"."experiment_comments"."status" IS '可见状态：VISIBLE / HIDDEN / DELETED';
COMMENT ON COLUMN "public"."experiment_comments"."create_time" IS '创建时间，插入时自动填充';
COMMENT ON COLUMN "public"."experiment_comments"."update_time" IS '更新时间，插入/更新时自动填充';
CREATE INDEX "idx_experiment_comments_experiment_created" ON "public"."experiment_comments" USING btree ("experiment_id", "create_time");
CREATE INDEX "idx_experiment_comments_owner" ON "public"."experiment_comments" USING btree ("owner_type", "owner_id");
CREATE INDEX "idx_experiment_comments_root" ON "public"."experiment_comments" USING btree ("root_id", "create_time");;

CREATE SEQUENCE IF NOT EXISTS "public"."experiments_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."experiments" (
  "id" bigint NOT NULL DEFAULT nextval('experiments_id_seq'::regclass),
  "route" character varying(64) NOT NULL,
  "title" character varying(120) NOT NULL,
  "subject_type" character varying(40) NOT NULL,
  "description" text NOT NULL,
  "cover_url" character varying(512),
  "topics" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "status" character varying(20) NOT NULL DEFAULT 'PUBLISHED'::character varying,
  "visitor_count" bigint NOT NULL DEFAULT 0,
  "favorite_count" bigint NOT NULL DEFAULT 0,
  "view_count" bigint NOT NULL DEFAULT 0,
  "comment_count" bigint NOT NULL DEFAULT 0,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "subject_type_id" bigint NOT NULL,
  PRIMARY KEY ("id")
);

COMMENT ON COLUMN "public"."experiments"."id" IS '实验 ID，自增主键';
COMMENT ON COLUMN "public"."experiments"."route" IS '路由 slug，唯一，与用户端 3D 页面 registry key 一致';
COMMENT ON COLUMN "public"."experiments"."title" IS '实验标题';
COMMENT ON COLUMN "public"."experiments"."subject_type" IS '物理子学科 code 冗余字段（与 subject_types.code 同步，便于查询）';
COMMENT ON COLUMN "public"."experiments"."description" IS '实验简介';
COMMENT ON COLUMN "public"."experiments"."cover_url" IS '封面 URL（MinIO 或外链）；为空时前端 fallback';
COMMENT ON COLUMN "public"."experiments"."topics" IS '标签数组（JSONB）';
COMMENT ON COLUMN "public"."experiments"."status" IS '发布状态：PUBLISHED / DRAFT';
COMMENT ON COLUMN "public"."experiments"."visitor_count" IS '访客数（冗余统计）';
COMMENT ON COLUMN "public"."experiments"."favorite_count" IS '收藏数（冗余统计）';
COMMENT ON COLUMN "public"."experiments"."view_count" IS '浏览量（冗余统计）';
COMMENT ON COLUMN "public"."experiments"."comment_count" IS '评论数（冗余统计，预留）';
COMMENT ON COLUMN "public"."experiments"."create_time" IS '创建时间，插入时自动填充';
COMMENT ON COLUMN "public"."experiments"."update_time" IS '更新时间，插入/更新时自动填充';
COMMENT ON COLUMN "public"."experiments"."subject_type_id" IS '物理子学科 ID，逻辑关联 subject_types(id)';
CREATE UNIQUE INDEX "uk_experiments_route" ON "public"."experiments" USING btree ("route");;

CREATE SEQUENCE IF NOT EXISTS "public"."kb_chunks_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."kb_chunks" (
  "id" bigint NOT NULL DEFAULT nextval('kb_chunks_id_seq'::regclass),
  "document_id" bigint NOT NULL,
  "chunk_index" integer NOT NULL,
  "content" text NOT NULL,
  "embedding" vector(1024),
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

COMMENT ON COLUMN "public"."kb_chunks"."document_id" IS '文档 ID，逻辑关联 kb_documents(id)';
COMMENT ON COLUMN "public"."kb_chunks"."chunk_index" IS '文档内切片序号，从 0 起';
COMMENT ON COLUMN "public"."kb_chunks"."content" IS '切片正文';
COMMENT ON COLUMN "public"."kb_chunks"."embedding" IS '向量嵌入（pgvector）';
CREATE INDEX "idx_kb_chunks_document_id" ON "public"."kb_chunks" USING btree ("document_id");;

CREATE SEQUENCE IF NOT EXISTS "public"."kb_documents_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."kb_documents" (
  "id" bigint NOT NULL DEFAULT nextval('kb_documents_id_seq'::regclass),
  "title" character varying(200) NOT NULL,
  "filename" character varying(255) NOT NULL,
  "content_type" character varying(100),
  "status" character varying(20) NOT NULL DEFAULT 'READY'::character varying,
  "chunk_count" integer NOT NULL DEFAULT 0,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

COMMENT ON COLUMN "public"."kb_documents"."title" IS '知识库文档标题';
COMMENT ON COLUMN "public"."kb_documents"."filename" IS '原始文件名';
COMMENT ON COLUMN "public"."kb_documents"."status" IS 'PROCESSING / READY / FAILED';
COMMENT ON COLUMN "public"."kb_documents"."chunk_count" IS '切片数量';;

CREATE SEQUENCE IF NOT EXISTS "public"."subject_types_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."subject_types" (
  "id" bigint NOT NULL DEFAULT nextval('subject_types_id_seq'::regclass),
  "code" character varying(40) NOT NULL,
  "label" character varying(40) NOT NULL,
  "description" text,
  "sort_order" integer NOT NULL DEFAULT 0,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

COMMENT ON COLUMN "public"."subject_types"."id" IS '学科类型 ID，自增主键';
COMMENT ON COLUMN "public"."subject_types"."code" IS '枚举代码，如 MECHANICS、QUANTUM，与 experiments.subject_type 冗余字段同步';
COMMENT ON COLUMN "public"."subject_types"."label" IS '中文展示名，如 力学、量子';
COMMENT ON COLUMN "public"."subject_types"."description" IS '学科说明（可选）';
COMMENT ON COLUMN "public"."subject_types"."sort_order" IS '排序权重，越小越靠前';
COMMENT ON COLUMN "public"."subject_types"."create_time" IS '创建时间，插入时自动填充';
COMMENT ON COLUMN "public"."subject_types"."update_time" IS '更新时间，插入/更新时自动填充';
CREATE UNIQUE INDEX "uk_subject_types_code" ON "public"."subject_types" USING btree ("code");;

CREATE SEQUENCE IF NOT EXISTS "public"."users_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."users" (
  "id" bigint NOT NULL DEFAULT nextval('users_id_seq'::regclass),
  "username" character varying(20) NOT NULL,
  "password_hash" character varying(255) NOT NULL,
  "nickname" character varying(20) NOT NULL,
  "avatar_url" character varying(512),
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

COMMENT ON COLUMN "public"."users"."id" IS '用户 ID，自增主键';
COMMENT ON COLUMN "public"."users"."username" IS '登录用户名，唯一，长度 3–20';
COMMENT ON COLUMN "public"."users"."password_hash" IS '密码哈希（BCrypt）';
COMMENT ON COLUMN "public"."users"."nickname" IS '显示昵称；注册时默认写入 username';
COMMENT ON COLUMN "public"."users"."avatar_url" IS '头像地址，可选；为空时前端取 username 前 2 个字符展示文字头像';
COMMENT ON COLUMN "public"."users"."create_time" IS '创建时间，插入时自动填充';
COMMENT ON COLUMN "public"."users"."update_time" IS '更新时间，插入/更新时自动填充';
CREATE UNIQUE INDEX "uk_users_username" ON "public"."users" USING btree ("username");;

CREATE SEQUENCE IF NOT EXISTS "public"."ai_chat_messages_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."ai_chat_messages" (
  "id" bigint NOT NULL DEFAULT nextval('ai_chat_messages_id_seq'::regclass),
  "session_id" bigint NOT NULL,
  "role" character varying(20) NOT NULL,
  "content" text NOT NULL,
  "context_json" jsonb,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

COMMENT ON COLUMN "public"."ai_chat_messages"."session_id" IS '会话 ID，逻辑关联 ai_chat_sessions(id)';
COMMENT ON COLUMN "public"."ai_chat_messages"."role" IS 'user / assistant / system';
COMMENT ON COLUMN "public"."ai_chat_messages"."content" IS '消息正文';
COMMENT ON COLUMN "public"."ai_chat_messages"."context_json" IS '发消息时的页面上下文（可选）';
CREATE INDEX "idx_ai_chat_messages_session_id" ON "public"."ai_chat_messages" USING btree ("session_id", "id");;

CREATE TABLE "public"."announcements" (
  "id" bigint NOT NULL DEFAULT nextval('announcements_id_seq'::regclass),
  "title" character varying(100) NOT NULL,
  "content" text NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

COMMENT ON COLUMN "public"."announcements"."id" IS '?? ID?????';
COMMENT ON COLUMN "public"."announcements"."title" IS '????';
COMMENT ON COLUMN "public"."announcements"."content" IS '????';
COMMENT ON COLUMN "public"."announcements"."create_time" IS '????';
COMMENT ON COLUMN "public"."announcements"."update_time" IS '????';
CREATE INDEX "idx_announcements_create_time" ON "public"."announcements" USING btree ("create_time");;

CREATE SEQUENCE IF NOT EXISTS "public"."experiment_favorites_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."experiment_favorites" (
  "id" bigint NOT NULL DEFAULT nextval('experiment_favorites_id_seq'::regclass),
  "user_id" bigint NOT NULL,
  "experiment_id" bigint NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

COMMENT ON COLUMN "public"."experiment_favorites"."id" IS '收藏记录 ID，自增主键';
COMMENT ON COLUMN "public"."experiment_favorites"."user_id" IS '用户 ID，逻辑关联 users(id)';
COMMENT ON COLUMN "public"."experiment_favorites"."experiment_id" IS '实验 ID，逻辑关联 experiments(id)';
COMMENT ON COLUMN "public"."experiment_favorites"."create_time" IS '收藏时间，插入时自动填充';
CREATE UNIQUE INDEX "uk_experiment_favorites_user_experiment" ON "public"."experiment_favorites" USING btree ("user_id", "experiment_id");;

CREATE SEQUENCE IF NOT EXISTS "public"."ai_chat_sessions_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."ai_chat_sessions" (
  "id" bigint NOT NULL DEFAULT nextval('ai_chat_sessions_id_seq'::regclass),
  "owner_id" bigint NOT NULL,
  "owner_type" smallint NOT NULL,
  "title" character varying(200) NOT NULL DEFAULT '新对话'::character varying,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

COMMENT ON COLUMN "public"."ai_chat_sessions"."owner_id" IS '所有者 ID：owner_type=0 为 users.id；=1 为 admins.id';
COMMENT ON COLUMN "public"."ai_chat_sessions"."owner_type" IS '0=用户 USER，1=管理员 ADMIN';
COMMENT ON COLUMN "public"."ai_chat_sessions"."title" IS '会话标题（可用首条用户消息截断）';
CREATE INDEX "idx_ai_chat_sessions_owner_updated" ON "public"."ai_chat_sessions" USING btree ("owner_type", "owner_id", "update_time");;

CREATE SEQUENCE IF NOT EXISTS "public"."experiment_comment_likes_id_seq"
  AS bigint
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."experiment_comment_likes" (
  "id" bigint NOT NULL DEFAULT nextval('experiment_comment_likes_id_seq'::regclass),
  "comment_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "create_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

COMMENT ON COLUMN "public"."experiment_comment_likes"."id" IS '点赞记录 ID，自增主键';
COMMENT ON COLUMN "public"."experiment_comment_likes"."comment_id" IS '评论 ID，逻辑关联 experiment_comments(id)';
COMMENT ON COLUMN "public"."experiment_comment_likes"."user_id" IS '用户 ID，逻辑关联 users(id)';
COMMENT ON COLUMN "public"."experiment_comment_likes"."create_time" IS '点赞时间，插入时自动填充';
CREATE INDEX "idx_experiment_comment_likes_user" ON "public"."experiment_comment_likes" USING btree ("user_id");
CREATE UNIQUE INDEX "uk_experiment_comment_likes_comment_user" ON "public"."experiment_comment_likes" USING btree ("comment_id", "user_id");;

ALTER SEQUENCE "public"."admins_id_seq" OWNED BY "public"."admins"."id";

ALTER SEQUENCE "public"."ai_chat_messages_id_seq" OWNED BY "public"."ai_chat_messages"."id";

ALTER SEQUENCE "public"."ai_chat_sessions_id_seq" OWNED BY "public"."ai_chat_sessions"."id";

ALTER SEQUENCE "public"."experiment_comment_likes_id_seq" OWNED BY "public"."experiment_comment_likes"."id";

ALTER SEQUENCE "public"."experiment_comments_id_seq" OWNED BY "public"."experiment_comments"."id";

ALTER SEQUENCE "public"."experiment_favorites_id_seq" OWNED BY "public"."experiment_favorites"."id";

ALTER SEQUENCE "public"."experiments_id_seq" OWNED BY "public"."experiments"."id";

ALTER SEQUENCE "public"."kb_chunks_id_seq" OWNED BY "public"."kb_chunks"."id";

ALTER SEQUENCE "public"."kb_documents_id_seq" OWNED BY "public"."kb_documents"."id";

ALTER SEQUENCE "public"."subject_types_id_seq" OWNED BY "public"."subject_types"."id";

ALTER SEQUENCE "public"."users_id_seq" OWNED BY "public"."users"."id";

SELECT setval('"public"."admins_id_seq"', GREATEST(COALESCE(MAX("id"), 2), 2), true) FROM "public"."admins";

SELECT setval('"public"."ai_chat_messages_id_seq"', GREATEST(COALESCE(MAX("id"), 34), 34), true) FROM "public"."ai_chat_messages";

SELECT setval('"public"."ai_chat_sessions_id_seq"', GREATEST(COALESCE(MAX("id"), 21), 21), true) FROM "public"."ai_chat_sessions";

SELECT setval('"public"."announcements_id_seq"', 2, true);

SELECT setval('"public"."experiment_comment_likes_id_seq"', GREATEST(COALESCE(MAX("id"), 5), 5), true) FROM "public"."experiment_comment_likes";

SELECT setval('"public"."experiment_comments_id_seq"', GREATEST(COALESCE(MAX("id"), 7), 7), true) FROM "public"."experiment_comments";

SELECT setval('"public"."experiment_favorites_id_seq"', GREATEST(COALESCE(MAX("id"), 5), 5), true) FROM "public"."experiment_favorites";

SELECT setval('"public"."experiments_id_seq"', GREATEST(COALESCE(MAX("id"), 13), 13), true) FROM "public"."experiments";

SELECT setval('"public"."kb_chunks_id_seq"', GREATEST(COALESCE(MAX("id"), 4), 4), true) FROM "public"."kb_chunks";

SELECT setval('"public"."kb_documents_id_seq"', GREATEST(COALESCE(MAX("id"), 3), 3), true) FROM "public"."kb_documents";

SELECT setval('"public"."subject_types_id_seq"', GREATEST(COALESCE(MAX("id"), 16), 16), true) FROM "public"."subject_types";

SELECT setval('"public"."users_id_seq"', GREATEST(COALESCE(MAX("id"), 3), 3), true) FROM "public"."users";

CREATE OR REPLACE FUNCTION public.array_to_halfvec(integer[], integer, boolean)
 RETURNS halfvec
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$array_to_halfvec$function$;

CREATE OR REPLACE FUNCTION public.array_to_halfvec(integer[], integer, boolean)
 RETURNS halfvec
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$array_to_halfvec$function$;

CREATE OR REPLACE FUNCTION public.array_to_halfvec(integer[], integer, boolean)
 RETURNS halfvec
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$array_to_halfvec$function$;

CREATE OR REPLACE FUNCTION public.array_to_halfvec(integer[], integer, boolean)
 RETURNS halfvec
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$array_to_halfvec$function$;

CREATE OR REPLACE FUNCTION public.array_to_sparsevec(integer[], integer, boolean)
 RETURNS sparsevec
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$array_to_sparsevec$function$;

CREATE OR REPLACE FUNCTION public.array_to_sparsevec(integer[], integer, boolean)
 RETURNS sparsevec
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$array_to_sparsevec$function$;

CREATE OR REPLACE FUNCTION public.array_to_sparsevec(integer[], integer, boolean)
 RETURNS sparsevec
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$array_to_sparsevec$function$;

CREATE OR REPLACE FUNCTION public.array_to_sparsevec(integer[], integer, boolean)
 RETURNS sparsevec
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$array_to_sparsevec$function$;

CREATE OR REPLACE FUNCTION public.array_to_vector(integer[], integer, boolean)
 RETURNS vector
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$array_to_vector$function$;

CREATE OR REPLACE FUNCTION public.array_to_vector(integer[], integer, boolean)
 RETURNS vector
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$array_to_vector$function$;

CREATE OR REPLACE FUNCTION public.array_to_vector(integer[], integer, boolean)
 RETURNS vector
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$array_to_vector$function$;

CREATE OR REPLACE FUNCTION public.array_to_vector(integer[], integer, boolean)
 RETURNS vector
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$array_to_vector$function$;

CREATE OR REPLACE FUNCTION public.binary_quantize(vector)
 RETURNS bit
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$binary_quantize$function$;

CREATE OR REPLACE FUNCTION public.binary_quantize(vector)
 RETURNS bit
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$binary_quantize$function$;

CREATE OR REPLACE FUNCTION public.cosine_distance(vector, vector)
 RETURNS double precision
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$cosine_distance$function$;

CREATE OR REPLACE FUNCTION public.cosine_distance(vector, vector)
 RETURNS double precision
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$cosine_distance$function$;

CREATE OR REPLACE FUNCTION public.cosine_distance(vector, vector)
 RETURNS double precision
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$cosine_distance$function$;

CREATE OR REPLACE FUNCTION public.halfvec(halfvec, integer, boolean)
 RETURNS halfvec
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$halfvec$function$;

CREATE OR REPLACE FUNCTION public.halfvec_accum(double precision[], halfvec)
 RETURNS double precision[]
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$halfvec_accum$function$;

CREATE OR REPLACE FUNCTION public.halfvec_add(halfvec, halfvec)
 RETURNS halfvec
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$halfvec_add$function$;

CREATE OR REPLACE FUNCTION public.halfvec_avg(double precision[])
 RETURNS halfvec
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$halfvec_avg$function$;

CREATE OR REPLACE FUNCTION public.halfvec_cmp(halfvec, halfvec)
 RETURNS integer
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$halfvec_cmp$function$;

CREATE OR REPLACE FUNCTION public.halfvec_combine(double precision[], double precision[])
 RETURNS double precision[]
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_combine$function$;

CREATE OR REPLACE FUNCTION public.halfvec_concat(halfvec, halfvec)
 RETURNS halfvec
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$halfvec_concat$function$;

CREATE OR REPLACE FUNCTION public.halfvec_eq(halfvec, halfvec)
 RETURNS boolean
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$halfvec_eq$function$;

CREATE OR REPLACE FUNCTION public.halfvec_ge(halfvec, halfvec)
 RETURNS boolean
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$halfvec_ge$function$;

CREATE OR REPLACE FUNCTION public.halfvec_gt(halfvec, halfvec)
 RETURNS boolean
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$halfvec_gt$function$;

CREATE OR REPLACE FUNCTION public.halfvec_in(cstring, oid, integer)
 RETURNS halfvec
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$halfvec_in$function$;

CREATE OR REPLACE FUNCTION public.halfvec_l2_squared_distance(halfvec, halfvec)
 RETURNS double precision
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$halfvec_l2_squared_distance$function$;

CREATE OR REPLACE FUNCTION public.halfvec_le(halfvec, halfvec)
 RETURNS boolean
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$halfvec_le$function$;

CREATE OR REPLACE FUNCTION public.halfvec_lt(halfvec, halfvec)
 RETURNS boolean
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$halfvec_lt$function$;

CREATE OR REPLACE FUNCTION public.halfvec_mul(halfvec, halfvec)
 RETURNS halfvec
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$halfvec_mul$function$;

CREATE OR REPLACE FUNCTION public.halfvec_ne(halfvec, halfvec)
 RETURNS boolean
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$halfvec_ne$function$;

CREATE OR REPLACE FUNCTION public.halfvec_negative_inner_product(halfvec, halfvec)
 RETURNS double precision
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$halfvec_negative_inner_product$function$;

CREATE OR REPLACE FUNCTION public.halfvec_out(halfvec)
 RETURNS cstring
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$halfvec_out$function$;

CREATE OR REPLACE FUNCTION public.halfvec_recv(internal, oid, integer)
 RETURNS halfvec
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$halfvec_recv$function$;

CREATE OR REPLACE FUNCTION public.halfvec_send(halfvec)
 RETURNS bytea
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$halfvec_send$function$;

CREATE OR REPLACE FUNCTION public.halfvec_spherical_distance(halfvec, halfvec)
 RETURNS double precision
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$halfvec_spherical_distance$function$;

CREATE OR REPLACE FUNCTION public.halfvec_sub(halfvec, halfvec)
 RETURNS halfvec
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$halfvec_sub$function$;

CREATE OR REPLACE FUNCTION public.halfvec_to_float4(halfvec, integer, boolean)
 RETURNS real[]
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$halfvec_to_float4$function$;

CREATE OR REPLACE FUNCTION public.halfvec_to_sparsevec(halfvec, integer, boolean)
 RETURNS sparsevec
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$halfvec_to_sparsevec$function$;

CREATE OR REPLACE FUNCTION public.halfvec_to_vector(halfvec, integer, boolean)
 RETURNS vector
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$halfvec_to_vector$function$;

CREATE OR REPLACE FUNCTION public.halfvec_typmod_in(cstring[])
 RETURNS integer
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$halfvec_typmod_in$function$;

CREATE OR REPLACE FUNCTION public.hamming_distance(bit, bit)
 RETURNS double precision
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$hamming_distance$function$;

CREATE OR REPLACE FUNCTION public.hnsw_bit_support(internal)
 RETURNS internal
 LANGUAGE c
AS '$libdir/vector', $function$hnsw_bit_support$function$;

CREATE OR REPLACE FUNCTION public.hnsw_halfvec_support(internal)
 RETURNS internal
 LANGUAGE c
AS '$libdir/vector', $function$hnsw_halfvec_support$function$;

CREATE OR REPLACE FUNCTION public.hnsw_sparsevec_support(internal)
 RETURNS internal
 LANGUAGE c
AS '$libdir/vector', $function$hnsw_sparsevec_support$function$;

CREATE OR REPLACE FUNCTION public.hnswhandler(internal)
 RETURNS index_am_handler
 LANGUAGE c
AS '$libdir/vector', $function$hnswhandler$function$;

CREATE OR REPLACE FUNCTION public.inner_product(vector, vector)
 RETURNS double precision
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$inner_product$function$;

CREATE OR REPLACE FUNCTION public.inner_product(vector, vector)
 RETURNS double precision
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$inner_product$function$;

CREATE OR REPLACE FUNCTION public.inner_product(vector, vector)
 RETURNS double precision
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$inner_product$function$;

CREATE OR REPLACE FUNCTION public.ivfflat_bit_support(internal)
 RETURNS internal
 LANGUAGE c
AS '$libdir/vector', $function$ivfflat_bit_support$function$;

CREATE OR REPLACE FUNCTION public.ivfflat_halfvec_support(internal)
 RETURNS internal
 LANGUAGE c
AS '$libdir/vector', $function$ivfflat_halfvec_support$function$;

CREATE OR REPLACE FUNCTION public.ivfflathandler(internal)
 RETURNS index_am_handler
 LANGUAGE c
AS '$libdir/vector', $function$ivfflathandler$function$;

CREATE OR REPLACE FUNCTION public.jaccard_distance(bit, bit)
 RETURNS double precision
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$jaccard_distance$function$;

CREATE OR REPLACE FUNCTION public.l1_distance(vector, vector)
 RETURNS double precision
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$l1_distance$function$;

CREATE OR REPLACE FUNCTION public.l1_distance(vector, vector)
 RETURNS double precision
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$l1_distance$function$;

CREATE OR REPLACE FUNCTION public.l1_distance(vector, vector)
 RETURNS double precision
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$l1_distance$function$;

CREATE OR REPLACE FUNCTION public.l2_distance(vector, vector)
 RETURNS double precision
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$l2_distance$function$;

CREATE OR REPLACE FUNCTION public.l2_distance(vector, vector)
 RETURNS double precision
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$l2_distance$function$;

CREATE OR REPLACE FUNCTION public.l2_distance(vector, vector)
 RETURNS double precision
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$l2_distance$function$;

CREATE OR REPLACE FUNCTION public.l2_norm(halfvec)
 RETURNS double precision
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$halfvec_l2_norm$function$;

CREATE OR REPLACE FUNCTION public.l2_norm(halfvec)
 RETURNS double precision
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$halfvec_l2_norm$function$;

CREATE OR REPLACE FUNCTION public.l2_normalize(vector)
 RETURNS vector
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$l2_normalize$function$;

CREATE OR REPLACE FUNCTION public.l2_normalize(vector)
 RETURNS vector
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$l2_normalize$function$;

CREATE OR REPLACE FUNCTION public.l2_normalize(vector)
 RETURNS vector
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$l2_normalize$function$;

CREATE OR REPLACE FUNCTION public.sparsevec(sparsevec, integer, boolean)
 RETURNS sparsevec
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$sparsevec$function$;

CREATE OR REPLACE FUNCTION public.sparsevec_cmp(sparsevec, sparsevec)
 RETURNS integer
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$sparsevec_cmp$function$;

CREATE OR REPLACE FUNCTION public.sparsevec_eq(sparsevec, sparsevec)
 RETURNS boolean
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$sparsevec_eq$function$;

CREATE OR REPLACE FUNCTION public.sparsevec_ge(sparsevec, sparsevec)
 RETURNS boolean
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$sparsevec_ge$function$;

CREATE OR REPLACE FUNCTION public.sparsevec_gt(sparsevec, sparsevec)
 RETURNS boolean
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$sparsevec_gt$function$;

CREATE OR REPLACE FUNCTION public.sparsevec_in(cstring, oid, integer)
 RETURNS sparsevec
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$sparsevec_in$function$;

CREATE OR REPLACE FUNCTION public.sparsevec_l2_squared_distance(sparsevec, sparsevec)
 RETURNS double precision
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$sparsevec_l2_squared_distance$function$;

CREATE OR REPLACE FUNCTION public.sparsevec_le(sparsevec, sparsevec)
 RETURNS boolean
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$sparsevec_le$function$;

CREATE OR REPLACE FUNCTION public.sparsevec_lt(sparsevec, sparsevec)
 RETURNS boolean
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$sparsevec_lt$function$;

CREATE OR REPLACE FUNCTION public.sparsevec_ne(sparsevec, sparsevec)
 RETURNS boolean
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$sparsevec_ne$function$;

CREATE OR REPLACE FUNCTION public.sparsevec_negative_inner_product(sparsevec, sparsevec)
 RETURNS double precision
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$sparsevec_negative_inner_product$function$;

CREATE OR REPLACE FUNCTION public.sparsevec_out(sparsevec)
 RETURNS cstring
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$sparsevec_out$function$;

CREATE OR REPLACE FUNCTION public.sparsevec_recv(internal, oid, integer)
 RETURNS sparsevec
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$sparsevec_recv$function$;

CREATE OR REPLACE FUNCTION public.sparsevec_send(sparsevec)
 RETURNS bytea
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$sparsevec_send$function$;

CREATE OR REPLACE FUNCTION public.sparsevec_to_halfvec(sparsevec, integer, boolean)
 RETURNS halfvec
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$sparsevec_to_halfvec$function$;

CREATE OR REPLACE FUNCTION public.sparsevec_to_vector(sparsevec, integer, boolean)
 RETURNS vector
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$sparsevec_to_vector$function$;

CREATE OR REPLACE FUNCTION public.sparsevec_typmod_in(cstring[])
 RETURNS integer
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$sparsevec_typmod_in$function$;

CREATE OR REPLACE FUNCTION public.subvector(vector, integer, integer)
 RETURNS vector
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$subvector$function$;

CREATE OR REPLACE FUNCTION public.subvector(vector, integer, integer)
 RETURNS vector
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$subvector$function$;

CREATE OR REPLACE FUNCTION public.vector(vector, integer, boolean)
 RETURNS vector
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector$function$;

CREATE OR REPLACE FUNCTION public.vector_accum(double precision[], vector)
 RETURNS double precision[]
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_accum$function$;

CREATE OR REPLACE FUNCTION public.vector_add(vector, vector)
 RETURNS vector
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_add$function$;

CREATE OR REPLACE FUNCTION public.vector_avg(double precision[])
 RETURNS vector
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_avg$function$;

CREATE OR REPLACE FUNCTION public.vector_cmp(vector, vector)
 RETURNS integer
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_cmp$function$;

CREATE OR REPLACE FUNCTION public.vector_combine(double precision[], double precision[])
 RETURNS double precision[]
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_combine$function$;

CREATE OR REPLACE FUNCTION public.vector_concat(vector, vector)
 RETURNS vector
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_concat$function$;

CREATE OR REPLACE FUNCTION public.vector_dims(vector)
 RETURNS integer
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_dims$function$;

CREATE OR REPLACE FUNCTION public.vector_dims(vector)
 RETURNS integer
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_dims$function$;

CREATE OR REPLACE FUNCTION public.vector_eq(vector, vector)
 RETURNS boolean
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_eq$function$;

CREATE OR REPLACE FUNCTION public.vector_ge(vector, vector)
 RETURNS boolean
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_ge$function$;

CREATE OR REPLACE FUNCTION public.vector_gt(vector, vector)
 RETURNS boolean
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_gt$function$;

CREATE OR REPLACE FUNCTION public.vector_in(cstring, oid, integer)
 RETURNS vector
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_in$function$;

CREATE OR REPLACE FUNCTION public.vector_l2_squared_distance(vector, vector)
 RETURNS double precision
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_l2_squared_distance$function$;

CREATE OR REPLACE FUNCTION public.vector_le(vector, vector)
 RETURNS boolean
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_le$function$;

CREATE OR REPLACE FUNCTION public.vector_lt(vector, vector)
 RETURNS boolean
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_lt$function$;

CREATE OR REPLACE FUNCTION public.vector_mul(vector, vector)
 RETURNS vector
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_mul$function$;

CREATE OR REPLACE FUNCTION public.vector_ne(vector, vector)
 RETURNS boolean
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_ne$function$;

CREATE OR REPLACE FUNCTION public.vector_negative_inner_product(vector, vector)
 RETURNS double precision
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_negative_inner_product$function$;

CREATE OR REPLACE FUNCTION public.vector_norm(vector)
 RETURNS double precision
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_norm$function$;

CREATE OR REPLACE FUNCTION public.vector_out(vector)
 RETURNS cstring
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_out$function$;

CREATE OR REPLACE FUNCTION public.vector_recv(internal, oid, integer)
 RETURNS vector
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_recv$function$;

CREATE OR REPLACE FUNCTION public.vector_send(vector)
 RETURNS bytea
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_send$function$;

CREATE OR REPLACE FUNCTION public.vector_spherical_distance(vector, vector)
 RETURNS double precision
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_spherical_distance$function$;

CREATE OR REPLACE FUNCTION public.vector_sub(vector, vector)
 RETURNS vector
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_sub$function$;

CREATE OR REPLACE FUNCTION public.vector_to_float4(vector, integer, boolean)
 RETURNS real[]
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_to_float4$function$;

CREATE OR REPLACE FUNCTION public.vector_to_halfvec(vector, integer, boolean)
 RETURNS halfvec
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_to_halfvec$function$;

CREATE OR REPLACE FUNCTION public.vector_to_sparsevec(vector, integer, boolean)
 RETURNS sparsevec
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_to_sparsevec$function$;

CREATE OR REPLACE FUNCTION public.vector_typmod_in(cstring[])
 RETURNS integer
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/vector', $function$vector_typmod_in$function$;

