server:
  port: ${phys-lab.server.port}

spring:
  application:
    name: backend
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  datasource:
    driver-class-name: ${phys-lab.datasource.driver-class-name}
    url: jdbc:postgresql://${phys-lab.datasource.host}:${phys-lab.datasource.port}/${phys-lab.datasource.database}
    username: ${phys-lab.datasource.username}
    password: ${phys-lab.datasource.password}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: ${phys-lab.mybatis.log-impl}
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:/mapper/**/*.xml

phys-lab:
  jwt:
    secret: phys-lab-3d
    expiration-ms: 86400000

dromara:
  x-file-storage:
    default-platform: minio-1
    minio:
      - platform: minio-1
        enable-storage: true
        access-key: ${phys-lab.minio.access-key}
        secret-key: ${phys-lab.minio.secret-key}
        end-point: ${phys-lab.minio.endpoint}
        bucket-name: ${phys-lab.minio.bucket}
        domain: ${phys-lab.minio.domain}
        base-path: avatars/
      - platform: minio-covers
        enable-storage: true
        access-key: ${phys-lab.minio.access-key}
        secret-key: ${phys-lab.minio.secret-key}
        end-point: ${phys-lab.minio.endpoint}
        bucket-name: ${phys-lab.minio.bucket}
        domain: ${phys-lab.minio.domain}
        base-path: covers/
